# Generated by Django 5.2 on 2025-04-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_otp_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
